framework:
    mailer:
        # dsn: 'null://null'
        dsn: '%env(MAILER_DSN)%'
        envelope:
            # sender: 'contact@SnowTricks.com'
            # recipients: ['noah.fox@yopmail.com']
        headers:
            # from: 'SnowTricks <contact@SnowTricks.com>'