twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/public/css': styles

when@test:
    twig:
        strict_variables: true
        form_themes:
            - 'form/_collection_widget.html.twig'