monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            channels: ['!mailer']
        grouped:
            type: group
            members: [nested, streamed]
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        streamed:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: critical
        app_mailer:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.mailer.log"
            level: critical
            channels: ['mailer']
